//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoLog
    {
        public int id { get; set; }
        public Nullable<int> userId { get; set; }
        public int NodeId { get; set; }
        public string entityType { get; set; }
        public System.DateTime Datestamp { get; set; }
        public string logHeader { get; set; }
        public string logComment { get; set; }
        public string parameters { get; set; }
    
        public virtual umbracoUser umbracoUser { get; set; }
    }
}
