//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoContentVersion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoContentVersion()
        {
            this.umbracoContentVersionCultureVariation = new HashSet<umbracoContentVersionCultureVariation>();
            this.umbracoPropertyData = new HashSet<umbracoPropertyData>();
        }
    
        public int id { get; set; }
        public int nodeId { get; set; }
        public System.DateTime versionDate { get; set; }
        public Nullable<int> userId { get; set; }
        public bool current { get; set; }
        public string text { get; set; }
    
        public virtual umbracoContent umbracoContent { get; set; }
        public virtual umbracoUser umbracoUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoContentVersionCultureVariation> umbracoContentVersionCultureVariation { get; set; }
        public virtual umbracoDocumentVersion umbracoDocumentVersion { get; set; }
        public virtual umbracoMediaVersion umbracoMediaVersion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoPropertyData> umbracoPropertyData { get; set; }
    }
}
