//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoContent()
        {
            this.cmsContentNu = new HashSet<cmsContentNu>();
            this.cmsTagRelationship = new HashSet<cmsTagRelationship>();
            this.umbracoContentSchedule = new HashSet<umbracoContentSchedule>();
            this.umbracoContentVersion = new HashSet<umbracoContentVersion>();
        }
    
        public int nodeId { get; set; }
        public int contentTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsContentNu> cmsContentNu { get; set; }
        public virtual cmsMember cmsMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTagRelationship> cmsTagRelationship { get; set; }
        public virtual umbracoNode umbracoNode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoContentSchedule> umbracoContentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoContentVersion> umbracoContentVersion { get; set; }
        public virtual umbracoDocument umbracoDocument { get; set; }
    }
}
