//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoDocumentVersion
    {
        public int id { get; set; }
        public Nullable<int> templateId { get; set; }
        public bool published { get; set; }
    
        public virtual umbracoContentVersion umbracoContentVersion { get; set; }
    }
}
