//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoConsent
    {
        public int id { get; set; }
        public bool current { get; set; }
        public string source { get; set; }
        public string context { get; set; }
        public string action { get; set; }
        public System.DateTime createDate { get; set; }
        public int state { get; set; }
        public string comment { get; set; }
    }
}
