//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoLanguage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoLanguage()
        {
            this.cmsLanguageText = new HashSet<cmsLanguageText>();
            this.cmsTags = new HashSet<cmsTags>();
            this.umbracoContentSchedule = new HashSet<umbracoContentSchedule>();
            this.umbracoContentVersionCultureVariation = new HashSet<umbracoContentVersionCultureVariation>();
            this.umbracoDocumentCultureVariation = new HashSet<umbracoDocumentCultureVariation>();
            this.umbracoLanguage1 = new HashSet<umbracoLanguage>();
            this.umbracoPropertyData = new HashSet<umbracoPropertyData>();
        }
    
        public int id { get; set; }
        public string languageISOCode { get; set; }
        public string languageCultureName { get; set; }
        public bool isDefaultVariantLang { get; set; }
        public bool mandatory { get; set; }
        public Nullable<int> fallbackLanguageId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsLanguageText> cmsLanguageText { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTags> cmsTags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoContentSchedule> umbracoContentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoContentVersionCultureVariation> umbracoContentVersionCultureVariation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoDocumentCultureVariation> umbracoDocumentCultureVariation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoLanguage> umbracoLanguage1 { get; set; }
        public virtual umbracoLanguage umbracoLanguage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoPropertyData> umbracoPropertyData { get; set; }
    }
}
