//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoContentVersionCultureVariation
    {
        public int id { get; set; }
        public int versionId { get; set; }
        public int languageId { get; set; }
        public string name { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> availableUserId { get; set; }
    
        public virtual umbracoContentVersion umbracoContentVersion { get; set; }
        public virtual umbracoLanguage umbracoLanguage { get; set; }
        public virtual umbracoUser umbracoUser { get; set; }
    }
}
