//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoAudit
    {
        public int id { get; set; }
        public int performingUserId { get; set; }
        public string performingDetails { get; set; }
        public string performingIp { get; set; }
        public System.DateTime eventDateUtc { get; set; }
        public int affectedUserId { get; set; }
        public string affectedDetails { get; set; }
        public string eventType { get; set; }
        public string eventDetails { get; set; }
    }
}
