//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoDataType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoDataType()
        {
            this.cmsPropertyType = new HashSet<cmsPropertyType>();
        }
    
        public int nodeId { get; set; }
        public string propertyEditorAlias { get; set; }
        public string dbType { get; set; }
        public string config { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsPropertyType> cmsPropertyType { get; set; }
        public virtual umbracoNode umbracoNode { get; set; }
    }
}
