//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cnxdevsoft.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoUserLogin
    {
        public System.Guid sessionId { get; set; }
        public int userId { get; set; }
        public System.DateTime loggedInUtc { get; set; }
        public System.DateTime lastValidatedUtc { get; set; }
        public Nullable<System.DateTime> loggedOutUtc { get; set; }
        public string ipAddress { get; set; }
    
        public virtual umbracoUser umbracoUser { get; set; }
    }
}
